#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀 Running Lint Check..."
npm run lint
if [ $? -ne 0 ]; then
  echo "❌ Lint failed. Aborting commit."
  exit 1
fi

echo "🎨 Running Format Check..."
npm run format
git add .
if [ $? -ne 0 ]; then
  echo "❌ Format failed. Aborting commit."
  exit 1
fi

echo "🛠️  Running Build Check..."
npm run build
if [ $? -ne 0 ]; then
  echo "❌ Build failed. Aborting commit."
  exit 1
fi

echo "✅ All checks passed. Proceeding with commit!"
